### ISSUE TITLE
optimize D and G independently

### ISSUE THREAD

**Issue by ggsonic** [carpedm20/BEGAN-pytorch#4]
In the BEGAN paper ,it says:"Implementation note: while the updates are made simultaneously, they are still adversarial.  As such, it is important to optimize θD and θG independently with respect to their corresponding losses".
Maybe this will get better results?

**Comment by carpedm20** [comment]
Thanks for the comment! I tried but still didn't trained well. I also checked how G and D weights are changed when I only used G loss and D loss each (two separate execution of code) and the amount of weight changes are same with the current code so I thought it could be okay. I guess the gradient calculation of pytorch doesn't work as I expected.
